name: cd

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build Application
        run: scripts/buildprod.sh

      - name: setup-gcloud
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${{ github.workspace }}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-service-key.json
          gcloud --quiet config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud --quiet config set compute/zone ${{ secrets.GCP_COMPUTE_ZONE }}
          gcloud --quiet container clusters get-credentials ${{ secrets.GCP_GKE_CLUSTER }}
          

      - name: push Docker image to Google Container Registry
        run: gcloud builds submit --tag REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG .

        
